baseURL = 'https://ponnekanti.net/'
languageCode = 'en-gb'
title = 'Manav Ponnekanti'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  blog = "/:slug/"
